In [1]:
import numpy as np
A=np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal=A.sum(axis=0)
print(cal)
print(cal.reshape(1,4))

[ 59.  239.  155.4  76.9]
[[ 59.  239.  155.4  76.9]]


In [6]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [8]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c)
print(c.shape)

[[  2.25733702  -0.53757582 -14.14658307 ...   0.55796307   9.78355527
    1.67206374]
 [ 16.28598202   0.16968034 -13.21349294 ... -18.87323005 -23.30878618
    0.36278103]
 [-17.6278883  -12.08140871 -22.29795789 ... -11.47417407 -13.39561982
    3.3051853 ]
 ...
 [  1.60230473  14.63882059  19.43025982 ...  25.90087819  -7.76334381
  -23.69542052]
 [  2.65342747  -8.65838083   8.16376622 ...  21.56303487  16.45542268
    5.90340147]
 [  4.58076725  25.94748637  13.25222097 ...  14.52179725 -10.03226975
  -24.14034326]]
(12288, 45)
